server:
  port: 0

spring:
  application:
    name: lending-service
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/loan_db
    driverClassName: org.postgresql.Driver
    username: masik
    password: 121232
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
  instance:
    instance-id: ${spring.application.name}:${random.value}

resilience4j:
  circuitbreaker:
    instances:
      getStatusOrderCB:
        slidingWindowSize: 10
        slowCallDurationThreshold: 1s
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 60s
        automaticTransitionFromOpenToHalfOpenEnabled: false
        ignoreExceptions: java.lang.RuntimeException
  timelimiter:
    instances:
      oneSecTimeLimiter:
        timeout-duration: 1s

